[program:guacws]
directory=/etc/guacws
command=/etc/guacws/GLOKON.GuacWS.Server
autostart=true
autorestart=true
user=guacd
stderr_logfile=/var/log/guacws.err.log
stderr_logfile_maxbytes=50MB
stderr_logfile_backups=5
stdout_logfile=/var/log/guacws.out.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=5
