[program:guacd]
command=guacd -b 127.0.0.1 -l 4822 -f
autostart=true
autorestart=true
user=guacd
stderr_logfile=/var/log/guacd.err.log
stderr_logfile_maxbytes=50MB
stderr_logfile_backups=5
stdout_logfile=/var/log/guacd.out.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=5
