name: Build Server

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      publish:
        required: true
        type: boolean
      docker:
        required: true
        type: boolean
      dockerImage:
        required: true
        type: string
      dockerPlatform:
        required: true
        type: string
      operatingSystem:
        required: true
        type: string
      buildRuntime:
        required: true
        type: string
      tag:
        required: true
        type: string
      version:
        required: true
        type: string
      awsBucket:
        required: false
        type: string
      awsBucketRegion:
        required: false
        type: string
    secrets:
      token:
        required: false
      awsRole:
        required: false
      dockerHubUsername:
        required: false
      dockerHubPassword:
        required: false

permissions:
  id-token: write
  contents: write

env:
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

jobs:
  build-server:
    runs-on: ${{ inputs.operatingSystem }}

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.buildRuntime }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Configure AWS credentials
        if: inputs.publish == true
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.awsRole }}
          aws-region: ${{ inputs.awsBucketRegion }}
      
      - name: (Docker) Login to DockerHub
        if: inputs.publish == true && inputs.docker == true
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.dockerHubUsername }}
          password: ${{ secrets.dockerHubPassword }}
          
      - name: (Docker) Set up QEMU
        if: inputs.docker == true
        uses: docker/setup-qemu-action@v4

      - name: (Docker) Set up Docker Buildx
        if: inputs.docker == true
        uses: docker/setup-buildx-action@v3
        
      - name: (Docker) Prepare Docker Platform
        if: inputs.docker == true
        run: |
          platform=${{ inputs.dockerPlatform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV
          
      - name: (Docker) Extract metadata (tags, labels)
        if: inputs.docker == true
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.dockerImage }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}},value=${{ inputs.tag }}
            type=semver,pattern={{major}}.{{minor}},value=${{ inputs.tag }}

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Build Server
        run: dotnet publish ./GLOKON.GuacWS.Server/GLOKON.GuacWS.Server.csproj -p:AssemblyVersion="${{ inputs.version }}.0" --configuration Release --runtime ${{ inputs.buildRuntime }} --output ./dist

      - name: (Docker) Build (validate only, no push)
        if: inputs.docker == true && inputs.publish == false
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: ${{ inputs.dockerPlatform }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          labels: ${{ steps.meta.outputs.labels }}
          push: false

      - name: (Docker) Build and push by digest
        if: inputs.docker == true && inputs.publish == true
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: ${{ inputs.dockerPlatform }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,"name=${{ inputs.dockerImage }}",push-by-digest=true,name-canonical=true,push=true

      - name: (Docker) Export digest
        if: inputs.docker == true && inputs.publish == true
        run: |
          mkdir -p ${{ runner.temp }}/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "${{ runner.temp }}/digests/${digest#sha256:}"

      - name: Upload digest
        if: inputs.docker == true && inputs.publish == true
        uses: actions/upload-artifact@v7
        with:
          name: digests-${{ env.PLATFORM_PAIR }}
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1

      - uses: vimtor/action-zip@v1.3
        if: inputs.publish == true
        with:
          files: dist/
          dest: guacws-next-${{ inputs.buildRuntime }}-${{ inputs.version }}.zip

      - name: (GitHub) Upload Asset
        if: inputs.publish == true
        env:
            GITHUB_TOKEN: ${{ secrets.token }}
        run: gh release upload ${{ inputs.tag }} ./guacws-next-${{ inputs.buildRuntime }}-${{ inputs.version }}.zip

      - name: (S3) Upload Asset
        if: inputs.publish == true
        run: |
          aws s3 cp ./guacws-next-${{ inputs.buildRuntime }}-${{ inputs.version }}.zip s3://${{ inputs.awsBucket }}/guacws-next/${{ inputs.version }}/${{ inputs.buildRuntime }}.zip